version: '3.8'

services:
  bookstore-api:
    image: postgres
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=bookstore
